### ISSUE TITLE
bug: -352，信息：风控校验失败

### ISSUE THREAD

**Issue by ArenaDruid** [sunrisewestern/bilipod#6]
使用docker部署

已经提供cookies，并且在log中显示
```
2024-10-30 03:00:36.972 | INFO     | bilipod.utils.login:get_credential:53 - Welcome, {XX用户名XX}
```

以下是报错日志
```
2024-10-30 03:00:34.979 | INFO     | bilipod.main:run_service:56 - 

.______    __   __       __  .______     ______    _______

|   _  \  |  | |  |     |  | |   _  \   /  __  \  |       \

|  |_)  | |  | |  |     |  | |  |_)  | |  |  |  | |  .--.  |

|   _  <  |  | |  |     |  | |   ___/  |  |  |  | |  |  |  |

|  |_)  | |  | |  `----.|  | |  |      |  `--'  | |  '--'  |

|______/  |__| |_______||__| | _|       \______/  |_______/

2024-10-30 03:00:34.980 | INFO     | bilipod.main:run_service:57 - Start initializing...

2024-10-30 03:00:34.981 | INFO     | bilipod.executing.initialize:data_initialize:33 - Initializing feed: hong_se_huan_xiang_xiang...

2024-10-30 03:00:34.981 | INFO     | bilipod.executing.web_server:run_web_server:42 - Web server running at: https://bilipod.arenadruid.top/

Traceback (most recent call last):

  File "/usr/local/bin/bilipod", line 8, in <module>

    sys.exit(main())

             ^^^^^^

  File "/usr/local/lib/python3.12/site-packages/bilipod/main.py", line 151, in main

    asyncio.run(run_service(config, args.db))

  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/bilipod/main.py", line 88, in run_service

    await data_initialize(

  File "/usr/local/lib/python3.12/site-packages/bilipod/executing/initialize.py", line 45, in data_initialize

    pod_info = await get_pod_info(

               ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/bilipod/utils/biliuser.py", line 33, in get_pod_info

    info = await user_obj.get_user_info()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/bilibili_api/user.py", line 285, in get_user_info

    await Api(**API["info"]["info"], credential=self.credential)

  File "/usr/local/lib/python3.12/site-packages/bilibili_api/utils/network.py", line 273, in result

    self.__result = await self.request()

                    ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/bilibili_api/utils/network.py", line 173, in inner

    return await func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/bilibili_api/utils/network.py", line 558, in request

    real_data = self._process_response(

                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bilibili_api/utils/network.py", line 603, in _process_response
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-352，信息：风控校验失败。
{'code': -352, 'message': '风控校验失败', 'ttl': 1, 'data': {'v_voucher': 'voucher_08564dd2-ca2d-49a6-8b50-8bc43ccc2989'}}
Configuration loaded successfully.
```

**Comment by ArenaDruid** [comment]
https://github.com/DIYgod/RSSHub/issues/13985

**Comment by ArenaDruid** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/868

**Comment by ArenaDruid** [comment]
使用小号cookies依旧触发风控

**Comment by ArenaDruid** [comment]
https://github.com/Nemo2011/bilibili-api/issues/691

**Comment by sunrisewestern** [comment]
接口的问题，bilibili新加了风控参数。还在等 Nemo2011/bilibili-api#837

我把dev分支merge到main #7 了，可以运行，暂时绕过获取用户信息，但需要在config里手动填podcast的信息。不手动填 title会是uid，其他“unknown”


Optional feed customizations
    title: # "小约翰可汗-硬核狠人"
    description: # "等待鸽多"
    author: # "小约翰可汗"
    cover_art: # "{IMAGE_URL}"
    category: # "TV"
    subcategories: # "Documentary", "Tech News"
    explicit: # no
    lang: # "en"
    # optional: this will override the default link (usually the URL address) in the generated RSS feed with another link
    link: # "https://example.org"

**Comment by ArenaDruid** [comment]
我已经手动填写了podcast的信息，更新docker镜像后运行报错：

`An error occurred while loading the configuration: cannot access local variable 'token_data_update' where it is not associated with a value`

我没有修改config文件的其他地方，还有什么地方需要修改吗？

**Comment by ArenaDruid** [comment]
> 我已经手动填写了podcast的信息，更新docker镜像后运行报错：
> 
> `An error occurred while loading the configuration: cannot access local variable 'token_data_update' where it is not associated with a value`
> 
> 我没有修改config文件的其他地方，还有什么地方需要修改吗？

留意到了新的config文件，正在修改

**Comment by ArenaDruid** [comment]
修改了config之后，报错依然存在

附上config.yaml和docker-compose设置:

[config.yaml.txt](https://github.com/user-attachments/files/17567214/config.yaml.txt)
```
---
# This is an example of yaml configuration file for bilipod.

# Web server related configuration.
server:
  # HTTP server port.
  port: 5728

  # Optional. If you want to hide Podsync behind reverse proxy like nginx, you can use this field.
  # Server will be accessible from http://{bind_address}:{port}, but episode links will point to this URL {hostname}.
  hostname: {hostname}
  # Bind a specific IP addresses for server, default is to bind localhost or  
  bind_address: "0.0.0.0"
  # Specify path for reverse proxy, default is "/" and only [A-Za-z0-9] is allowed.
  # path: "test"
  # Optional. If you want to use TLS, you must set the TLS flag and specify the certificate file and private key file.
  tls: false
  certificate_path: ""
  key_file_path: ""


# Configure where to store the episode data
storage:
  # Could be "local" (default) for the local file system
  type: local
  storage.local:
    data_dir: /app/data # Don't change if you run podsync via docker

token:
  # This is the token used to authenticate with the bilibili API
  # refer to https://nemo2011.github.io/bilibili-api/#/get-credential for more details
  bili_jct: {bili_jct}
  buvid3: {buvid3}
  buvid4: {buvid4}
  dedeuserid: {dedeuserid}
  sessdata: {essdata}
  ac_time_value: # optional
  cookie_file_path: # optional, use this if you want to use exported Netscape cookies

feeds:
  hong_se_huan_xiang_xiang:
    uid: 8803699
    sid: 1293511
    page_size: 3
    update_period: 24h
    format: audio
    playlist_sort: "desc"
    quality: low
    opml: True
    keep_last: 10
    private_feed: True
    #endorse: ['like']
    title: "红色幻想乡B号机形态"
    description: "红色幻想乡B号机形态"
    author: "红色幻想乡B号机形态"
    cover_art: "{IMAGE_URL}"
    category:  "TV"
    subcategories:  "News"
    explicit: no
    lang:  "en"
    # optional: this will override the default link (usually the URL address) in the generated RSS feed with another link
    link:  "https://space.bilibili.com/8803699"

```



```
    bilipod:
        image: sunrisewestern/bilipod:v0.4.2
        container_name: bilipod
        volumes:
            - ./config.yaml:/app/config.yaml
            - ./data:/app/data
            - ./logs:/app/logs
        ports:
            - "4181:5728"
        network_mode: bridge
        restart: unless-stopped
```

**Comment by sunrisewestern** [comment]
有一行缩进错了，现在应该没问题了， v0.4.2

**Comment by ArenaDruid** [comment]
能够成功下载并在rss显示了。（虽然报错还在）
```
2024-10-30 15:42:55.211 | INFO     | bilipod.main:run_service:58 - Start initializing...
2024-10-30 15:42:55.215 | INFO     | bilipod.executing.initialize:data_initialize:33 - Initializing feed: hong_se_huan_xiang_xiang...
2024-10-30 15:42:55.216 | INFO     | bilipod.executing.web_server:run_web_server:42 - Web server running at: https://bilipod.arenadruid.top/
2024-10-30 15:42:55.951 | ERROR    | bilipod.utils.biliuser:get_pod_info:32 - Failed to get user info
2024-10-30 15:42:55.957 | ERROR    | bilipod.utils.biliuser:get_pod_info:33 - 接口返回错误代码：-352，信息：风控校验失败。
{'code': -352, 'message': '风控校验失败', 'ttl': 1, 'data': {'v_voucher': 'voucher_e09ff276-02da-4ebb-9fca-d7974b20d176'}}
2024-10-30 15:42:56.054 | INFO     | bilipod.executing.initialize:data_initialize:67 - Initializing download, 3 episodes found.
2024-10-30 15:43:23.288 | INFO     | bilipod.downloader.downloader:download_episodes:105 -  3 episodes downloaded successfully.
2024-10-30 15:43:23.300 | INFO     | bilipod.feed.podcast_rss:generate_feed_xml:89 - Generated feed for hong_se_huan_xiang_xiang
2024-10-30 15:43:23.302 | INFO     | bilipod.main:run_service:97 - Finished initializing...
2024-10-30 15:43:23.304 | INFO     | bilipod.main:run_service:103 - Starting scheduler...
```

**Comment by sunrisewestern** [comment]
之前测试忘记把Log level设成warning了，之后再一起改吧

**Comment by z0z0r4** [comment]
bilibili-api-python 已经很久没人维护了吧…release 都没发了，因为 pypi 发布流程炸了，owner 没处理…

建议直接 clone dev 分支安装了，我看 project.toml 好像还有安装一月份发的版本…

**Comment by ArenaDruid** [comment]
> bilibili-api-python 已经很久没人维护了吧…release 都没发了，因为 pypi 发布流程炸了，owner 没处理…
> 
> 建议直接 clone dev 分支安装了，我看 project.toml 好像还有安装一月份发的版本…

我看rsshub那边貌似可以暂时解决报错，但是没看用的什么接口。

**Comment by z0z0r4** [comment]
> 接口的问题，bilibili新加了风控参数。还在等 Nemo2011/bilibili-api#837
> 
> 我把dev分支merge到main #7 了，可以运行，暂时绕过获取用户信息，但需要在config里手动填podcast的信息。不手动填 title会是uid，其他“unknown”
> 
> 
> Optional feed customizations
>     title: # "小约翰可汗-硬核狠人"
>     description: # "等待鸽多"
>     author: # "小约翰可汗"
>     cover_art: # "{IMAGE_URL}"
>     category: # "TV"
>     subcategories: # "Documentary", "Tech News"
>     explicit: # no
>     lang: # "en"
>     # optional: this will override the default link (usually the URL address) in the generated RSS feed with another link
>     link: # "https://example.org"

这个等我晚点合并吧

**Comment by z0z0r4** [comment]
合并了

**Comment by sunrisewestern** [comment]
> 合并了

感谢。之前pypi上的功能都够就没改。
